# Generated by Django 4.1.5 on 2023-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.CharField(max_length=200000035, verbose_name='Savol')),
                ('to', models.CharField(max_length=23000000000000005, verbose_name='javob')),
                ('userid', models.CharField(max_length=30, verbose_name='userid')),
            ],
        ),
        migrations.CreateModel(
            name='nubm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=235, verbose_name='userid')),
                ('nubm', models.CharField(max_length=1000000000000, verbose_name='num')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=235, verbose_name='username')),
                ('password', models.CharField(max_length=235, verbose_name='password')),
                ('userid', models.CharField(max_length=30, verbose_name='id')),
            ],
        ),
    ]
